var menu ={
	main: [
		{url: "family", label: "Family Menu >"},
		{url: "games", label: "Games Menu >"},
		{url: "news", label: "News Menu >"},
		{url: "search", label: "Search Menu >"},
		{url: "weather", label: "Weather Menu >"},
	],
	family: [
		{url: "main", label: "< Main Menu"},
		{url: "https://bettyharmsen.github.io", label: "Betty's Favourite Links"},
		{url: "https://frharmsen.github.io", label: "Rick's Favourite Links"},
		{url: "https://www.flickr.com/photos/the-squirrel-whisperer/", label: "Rick's Pictures on Flickr"},
	],
	games: [
		{url: "main", label: "< Main Menu"},
		{url: "https://frharmsen.github.io/computer/apps/games/DealOrNoDeal", label: "Deal Or No Deal"},
		{url: "https://frharmsen.github.io/computer/apps/games/PegSolitaire/PegSolitaire.html", label: "Peg Solitaire"},
		{url: "https://frharmsen.github.io/computer/apps/games/VideoPoker", label: "VideoPoker"},
	],
	news: [
		{url: "main", label: "< Main Menu"},
		{url: "https://www.americanthinker.com/", label: "American Thinker"},
		{url: "https://www.counterpunch.org/", label: "CounterPunch"},
		{url: "https://www.theglobeandmail.com/", label: "Globe and Mail"},
		{url: "http://www.lfpress.com/", label: "London Free Press"},
		{url: "http://news.nationalpost.com/category/news/world", label: "National Post"},
		{url: "http://www.stthomastimesjournal.com/", label: "St. Thomas Times-Journal"},
		{url: "http://eedition.stthomastimesjournal.com/epaper/viewer.aspx", label: "St. Thomas Times-Journal e-edition"},
		{url: "https://www.thestar.com/", label: "Toronto Star"},
		{url: "http://torontosun.com/", label: "Toronto Sun"},
	],
	search: [
		{url: "main", label: "< Main Menu"},
		{url: "http://www.bing.com/", label: "Bing"},
		{url: "https://duckduckgo.com/", label: "DuckDuckGo"},
		{url: "https://www.google.ca/", label: "Google"},
		{url: "https://www.startpage.com/", label: "StartPage"},
		{url: "https://en.wikipedia.org/wiki/Main_Page", label: "Wikipedia"},
		{url: "https://ca.search.yahoo.com/", label: "Yahoo Search"},
	],
	weather: [
		{url: "main", label: "< Main Menu"},
		{url: "http://www.accuweather.com/en/ca/st-thomas/n5p/weather-forecast/54997", label: "AccuWeather - St. Thomas Weather"},
		{url: "http://weather.gc.ca/city/pages/on-98_metric_e.html", label: "Environment Canada - St. Thomas Weather"},
		{url: "https://www.theweathernetwork.com/ca/weather/ontario/st-thomas", label: "The Weather Network - St. Thomas"},
	],
};